name: GitHub Pages on push

on:
    pull_request:
        branches:
            - main
        types:
            - closed
    push:
      # only trigger on branches, not on tags
        branches: '**'

jobs:
    deploy_merged:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            deployments: write
            pages: write

        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '16.19'

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            # not production! CI=
            - name: Install dependencies
              run: cd ./client && CI= npm ci --ignore-scripts 
            # - run: CI= npm ci
            - run: cd ./client && CI= npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.9.0
              #  if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./client/build
